INSTALLED_APPS = [
    'dark',
    'dark.common',
    'dark.models',
    'dark.forms',
    'dark.views',
    'dark.urls',
    'dark.home',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
]
