# Generated by Django 3.2 on 2021-04-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('round', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_url', models.URLField(blank=True, default=None, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'ordering': ['team', 'round'],
                'unique_together': {('team', 'round')},
            },
        ),
    ]
