# Generated by Django 3.2.2 on 2021-05-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_tournament_access_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='access_key',
            field=models.IntegerField(default=8642, editable=False),
        ),
    ]
