name: Coverage Code Cov

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Generate Coverage Report
      run: |
        coverage run manage.py test
        coverage report
        coverage xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: 'ae0bf1f7-254f-420a-bb54-419a59f70c2b'
        fail_ci_if_error: true
